[phases.setup]
nixPkgs = ['nodejs', 'pnpm']

[phases.install]
cmds = ['pnpm install']

[phases.build]
cmds = ['pnpm run build']

[start]
cmd = "sh -c 'if [ \"$RUN_MIGRATIONS\" = \"true\" ]; then pnpm db:deploy; fi && pnpm start'"

[variables]
NODE_ENV = 'production'
RUN_MIGRATIONS = "true"